import { Salon, QueueToken, BusinessAccount } from './types';

export const INITIAL_BUSINESS_ACCOUNTS: BusinessAccount[] = [
  {
    id: 'acc-salon-vikram',
    businessName: 'The Royal Fade & Shave Studio',
    ownerName: 'Vikram Malhotra',
    phone: '+91 98111 22334',
    rawPhone: '9811122334',
    password: 'owner123',
    businessType: 'salon',
    salonId: 'salon-royal-fade',
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'acc-clinic-ananya',
    businessName: 'City Care Health & Dental Clinic',
    ownerName: 'Dr. Ananya Sen',
    phone: '+91 98222 33445',
    rawPhone: '9822233445',
    password: 'clinic123',
    businessType: 'clinic',
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'acc-rest-rajesh',
    businessName: 'Spice Hub Family Diner',
    ownerName: 'Chef Rajesh Sharma',
    phone: '+91 98333 44556',
    rawPhone: '9833344556',
    password: 'bistro123',
    businessType: 'restaurant',
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'acc-service-manoj',
    businessName: 'SpeedyWheels Automotive & Bike Service',
    ownerName: 'Manoj Kumar',
    phone: '+91 98444 55667',
    rawPhone: '9844455667',
    password: 'service123',
    businessType: 'service_center',
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'acc-gov-suresh',
    businessName: 'RTO & Civic Seva Kendra',
    ownerName: 'Suresh Verma',
    phone: '+91 98555 66778',
    rawPhone: '9855566778',
    password: 'gov123',
    businessType: 'government_office',
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
];

export const INITIAL_SALONS: Salon[] = [
  {
    id: 'salon-royal-fade',
    name: 'The Royal Fade & Shave Studio',
    tagline: 'Precision haircuts, beard sculpts & hot towel treatments',
    ownerName: 'Vikram Malhotra',
    phone: '+91 98450 12890',
    registeredPhone: '+91 98111 22334',
    ownerPhoto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    locality: 'Indiranagar 100ft Road',
    city: 'Bengaluru',
    address: '#482, 12th Main, HAL 2nd Stage, Indiranagar, Bengaluru 560038',
    rating: 4.8,
    totalReviews: 640,
    isOpen: true,
    openingHours: '8:00 AM – 9:00 PM',
    openingTime: '08:00 AM',
    closingTime: '09:00 PM',
    seatsCount: 4,
    activeBarbersCount: 4,
    image: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&auto=format&fit=crop&q=80',
    barbers: [
      {
        id: 'b1',
        name: 'Arun Kumar',
        avatar: '✂️',
        photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
        isAvailable: false,
        isActive: true,
        barberNumber: 'Barber A',
        seatNumber: 1,
      },
      {
        id: 'b2',
        name: 'Faisal Khan',
        avatar: '💈',
        photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
        isAvailable: false,
        isActive: true,
        barberNumber: 'Barber B',
        seatNumber: 2,
      },
      {
        id: 'b3',
        name: 'Ravi Teja',
        avatar: '🧔',
        photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
        isAvailable: false,
        isActive: true,
        barberNumber: 'Barber C',
        seatNumber: 3,
      },
      {
        id: 'b4_rf',
        name: 'Mohit Sen',
        avatar: '✂️',
        photo: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=200&auto=format&fit=crop&q=80',
        isAvailable: false,
        isActive: true,
        barberNumber: 'Barber D',
        seatNumber: 4,
      },
    ],
    services: [
      {
        id: 's1',
        name: 'Signature Skin Fade & Haircut',
        category: 'Hair',
        durationMins: 35,
        price: 399,
        description: 'Includes hair wash, precision clipper fade, scissor work, and styling pomade.',
      },
      {
        id: 's2',
        name: 'Beard Sculpting & Razor Edge',
        category: 'Beard',
        durationMins: 20,
        price: 249,
        description: 'Detailed beard shaping with hot foam razor edge alignment and organic beard oil.',
      },
      {
        id: 's3',
        name: 'Royal Combo (Haircut + Beard + Wash)',
        category: 'Hair',
        durationMins: 50,
        price: 599,
        description: 'Complete makeover with luxury hair wash, precision haircut, and custom beard trim.',
      },
      {
        id: 's4',
        name: 'Ayurvedic Head Massage with Kesh Oil',
        category: 'Spa',
        durationMins: 25,
        price: 299,
        description: 'Deep pressure point head massage followed by warm herbal steam towel therapy.',
      },
      {
        id: 's5',
        name: 'De-Tan Herbal Face Cleanup',
        category: 'Spa',
        durationMins: 30,
        price: 499,
        description: 'Fruit exfoliation, cooling aloe mask, and dead skin removal for clear skin.',
      },
      {
        id: 's6',
        name: 'Ammonia-Free Beard Color & Gloss',
        category: 'Color',
        durationMins: 25,
        price: 349,
        description: 'Natural black or dark brown tint with zero scalp or skin irritation.',
      },
    ],
  },
  {
    id: 'salon-classic-cp',
    name: 'Classic Men’s Barber & Grooming',
    tagline: 'Old-school British vintage grooming with modern scissor craft',
    ownerName: 'Devinder Singh',
    locality: 'Inner Circle, Connaught Place',
    city: 'New Delhi',
    address: 'Block C, Radial Road 3, Connaught Place, New Delhi 110001',
    rating: 4.7,
    totalReviews: 420,
    isOpen: true,
    openingHours: '10:00 AM – 9:00 PM',
    openingTime: '10:00 AM',
    closingTime: '09:00 PM',
    seatsCount: 2,
    activeBarbersCount: 2,
    phone: '+91 98112 43321',
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&auto=format&fit=crop&q=80',
    barbers: [
      { id: 'b4', name: 'Devinder Singh', avatar: '💈', isAvailable: true, isActive: true, barberNumber: 'Barber A', seatNumber: 1 },
      { id: 'b5', name: 'Manish Sharma', avatar: '✂️', isAvailable: true, isActive: true, barberNumber: 'Barber B', seatNumber: 2 },
    ],
    services: [
      {
        id: 'cp1',
        name: 'Executive Scissor Cut & Finish',
        category: 'Hair',
        durationMins: 30,
        price: 349,
        description: 'Classic side part, taper cut or textured crop with light mint rinse.',
      },
      {
        id: 'cp2',
        name: 'Traditional Hot Towel Wet Shave',
        category: 'Beard',
        durationMins: 25,
        price: 220,
        description: 'Two hot towels, pre-shave cream, badger brush lather, and alum block calm.',
      },
      {
        id: 'cp3',
        name: 'Charcoal Face Detox & Pack',
        category: 'Spa',
        durationMins: 25,
        price: 449,
        description: 'Extracts deep pore pollution dust and restores natural skin radiance.',
      },
    ],
  },
  {
    id: 'salon-envy-bandra',
    name: 'Envy Unisex Hair Studio',
    tagline: 'Celebrity style cuts, blowouts, balayage & scalp treatments',
    ownerName: 'Ken Fernandes',
    locality: 'Pali Hill, Bandra West',
    city: 'Mumbai',
    address: '14th Road, Near Khar Danda Road, Bandra West, Mumbai 400052',
    rating: 4.9,
    totalReviews: 890,
    isOpen: true,
    openingHours: '9:30 AM – 10:00 PM',
    openingTime: '09:30 AM',
    closingTime: '10:00 PM',
    seatsCount: 4,
    activeBarbersCount: 4,
    phone: '+91 99201 88410',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&auto=format&fit=crop&q=80',
    barbers: [
      { id: 'b6', name: 'Ken Fernandes', avatar: '✂️', isAvailable: true, isActive: true, barberNumber: 'Barber A', seatNumber: 1 },
      { id: 'b7', name: 'Priya Mehra', avatar: '💇‍♀️', isAvailable: true, isActive: true, barberNumber: 'Barber B', seatNumber: 2 },
      { id: 'b8', name: 'Samir Joshi', avatar: '💈', isAvailable: true, isActive: true, barberNumber: 'Barber C', seatNumber: 3 },
      { id: 'b9', name: 'Rohit Kadam', avatar: '🧔', isAvailable: true, isActive: true, barberNumber: 'Barber D', seatNumber: 4 },
    ],
    services: [
      {
        id: 'e1',
        name: 'Creative Layered / Textured Haircut',
        category: 'Hair',
        durationMins: 45,
        price: 650,
        description: 'Bespoke consultation, customized layering technique, and heat protection finish.',
      },
      {
        id: 'e2',
        name: 'Moroccan Oil Deep Conditioning Spa',
        category: 'Spa',
        durationMins: 40,
        price: 850,
        description: 'Intense hydration therapy repairing dry and sun-damaged hair ends.',
      },
      {
        id: 'e3',
        name: 'Beard Design & Luxury Ozone Steam',
        category: 'Beard',
        durationMins: 30,
        price: 400,
        description: 'Purifying ozone mist steam opening follicles followed by fine line contouring.',
      },
    ],
  },
];

export const INITIAL_QUEUES: Record<string, QueueToken[]> = {
  'salon-royal-fade': [
    {
      id: 'tok-rf-21',
      tokenNumber: 'B-21',
      ticketColor: 'orange',
      salonId: 'salon-royal-fade',
      salonName: 'The Royal Fade & Shave Studio',
      customerName: 'Rahul',
      customerPhone: '+91 98450 11223',
      services: [
        {
          id: 's1',
          name: 'Signature Skin Fade & Haircut',
          category: 'Hair',
          durationMins: 35,
          price: 399,
          description: 'Precision haircut & styling',
        },
      ],
      totalDurationMins: 35,
      totalPrice: 399,
      status: 'serving',
      createdAt: Date.now() - 25 * 60 * 1000,
      startedAt: Date.now() - 15 * 60 * 1000,
      barberName: 'Arun Kumar',
      assignedBarberId: 'b1',
    },
    {
      id: 'tok-rf-22',
      tokenNumber: 'B-22',
      ticketColor: 'pink',
      salonId: 'salon-royal-fade',
      salonName: 'The Royal Fade & Shave Studio',
      customerName: 'Amit',
      customerPhone: '+91 97401 55667',
      services: [
        {
          id: 's3',
          name: 'Royal Combo (Haircut + Beard + Wash)',
          category: 'Hair',
          durationMins: 50,
          price: 599,
          description: 'Haircut and beard sculpt',
        },
      ],
      totalDurationMins: 50,
      totalPrice: 599,
      status: 'serving',
      createdAt: Date.now() - 20 * 60 * 1000,
      startedAt: Date.now() - 10 * 60 * 1000,
      barberName: 'Faisal Khan',
      assignedBarberId: 'b2',
    },
    {
      id: 'tok-rf-23',
      tokenNumber: 'B-23',
      ticketColor: 'yellow',
      salonId: 'salon-royal-fade',
      salonName: 'The Royal Fade & Shave Studio',
      customerName: 'Mohit',
      customerPhone: '+91 99008 33441',
      services: [
        {
          id: 's2',
          name: 'Beard Sculpting & Razor Edge',
          category: 'Beard',
          durationMins: 20,
          price: 249,
          description: 'Beard shaping',
        },
      ],
      totalDurationMins: 20,
      totalPrice: 249,
      status: 'serving',
      createdAt: Date.now() - 16 * 60 * 1000,
      startedAt: Date.now() - 8 * 60 * 1000,
      barberName: 'Ravi Teja',
      assignedBarberId: 'b3',
    },
    {
      id: 'tok-rf-24',
      tokenNumber: 'B-24',
      ticketColor: 'purple',
      salonId: 'salon-royal-fade',
      salonName: 'The Royal Fade & Shave Studio',
      customerName: 'Ravi',
      customerPhone: '+91 98860 99882',
      services: [
        {
          id: 's1',
          name: 'Signature Skin Fade & Haircut',
          category: 'Hair',
          durationMins: 35,
          price: 399,
          description: 'Haircut',
        },
      ],
      totalDurationMins: 35,
      totalPrice: 399,
      status: 'serving',
      createdAt: Date.now() - 12 * 60 * 1000,
      startedAt: Date.now() - 5 * 60 * 1000,
      barberName: 'Mohit Sen',
      assignedBarberId: 'b4_rf',
    },
    {
      id: 'tok-rf-25',
      tokenNumber: 'B-25',
      ticketColor: 'blue',
      salonId: 'salon-royal-fade',
      salonName: 'The Royal Fade & Shave Studio',
      customerName: 'Karthik N.',
      customerPhone: '+91 96112 00192',
      services: [
        {
          id: 's4',
          name: 'Ayurvedic Head Massage with Kesh Oil',
          category: 'Spa',
          durationMins: 25,
          price: 299,
          description: 'Head massage',
        },
      ],
      totalDurationMins: 25,
      totalPrice: 299,
      status: 'waiting',
      createdAt: Date.now() - 6 * 60 * 1000,
    },
    {
      id: 'tok-rf-26',
      tokenNumber: 'B-26',
      ticketColor: 'coral',
      salonId: 'salon-royal-fade',
      salonName: 'The Royal Fade & Shave Studio',
      customerName: 'Siddharth Nair (Walk-in)',
      customerPhone: '+91 98860 11002',
      services: [
        {
          id: 's1',
          name: 'Signature Skin Fade & Haircut',
          category: 'Hair',
          durationMins: 35,
          price: 399,
          description: 'Skin fade',
        },
      ],
      totalDurationMins: 35,
      totalPrice: 399,
      status: 'waiting',
      isWalkIn: true,
      createdAt: Date.now() - 4 * 60 * 1000,
    },
    {
      id: 'tok-rf-27',
      tokenNumber: 'B-27',
      ticketColor: 'cyan',
      salonId: 'salon-royal-fade',
      salonName: 'The Royal Fade & Shave Studio',
      customerName: 'Aditya Sen',
      customerPhone: '+91 98450 77123',
      services: [
        {
          id: 's2',
          name: 'Beard Sculpting & Razor Edge',
          category: 'Beard',
          durationMins: 20,
          price: 249,
          description: 'Beard shaping',
        },
      ],
      totalDurationMins: 20,
      totalPrice: 249,
      status: 'waiting',
      createdAt: Date.now() - 2 * 60 * 1000,
    },
  ],
  'salon-classic-cp': [
    {
      id: 'tok-cp-01',
      tokenNumber: 'C-04',
      ticketColor: 'coral',
      salonId: 'salon-classic-cp',
      salonName: 'Classic Men’s Barber & Grooming',
      customerName: 'Gurpreet Singh',
      customerPhone: '+91 98101 22334',
      services: [
        {
          id: 'cp1',
          name: 'Executive Scissor Cut & Finish',
          category: 'Hair',
          durationMins: 30,
          price: 349,
          description: 'Scissor cut',
        },
      ],
      totalDurationMins: 30,
      totalPrice: 349,
      status: 'serving',
      createdAt: Date.now() - 15 * 60 * 1000,
      startedAt: Date.now() - 12 * 60 * 1000,
      barberName: 'Devinder Singh',
    },
    {
      id: 'tok-cp-02',
      tokenNumber: 'C-05',
      ticketColor: 'cyan',
      salonId: 'salon-classic-cp',
      salonName: 'Classic Men’s Barber & Grooming',
      customerName: 'Aman Deep',
      customerPhone: '+91 98711 77889',
      services: [
        {
          id: 'cp2',
          name: 'Traditional Hot Towel Wet Shave',
          category: 'Beard',
          durationMins: 25,
          price: 220,
          description: 'Hot towel shave',
        },
      ],
      totalDurationMins: 25,
      totalPrice: 220,
      status: 'waiting',
      createdAt: Date.now() - 5 * 60 * 1000,
    },
  ],
  'salon-envy-bandra': [
    {
      id: 'tok-env-01',
      tokenNumber: 'E-08',
      ticketColor: 'orange',
      salonId: 'salon-envy-bandra',
      salonName: 'Envy Unisex Hair Studio',
      customerName: 'Tanvi Shah',
      customerPhone: '+91 98200 44556',
      services: [
        {
          id: 'e1',
          name: 'Creative Layered / Textured Haircut',
          category: 'Hair',
          durationMins: 45,
          price: 650,
          description: 'Layered cut',
        },
      ],
      totalDurationMins: 45,
      totalPrice: 650,
      status: 'serving',
      createdAt: Date.now() - 20 * 60 * 1000,
      startedAt: Date.now() - 15 * 60 * 1000,
      barberName: 'Ken Fernandes',
    },
  ],
};
